### ISSUE TITLE
Lesson58 - Fatal Error

### ISSUE THREAD

**Issue by LifeSteala** [Alecaddd/WordPressPlugin101#13]
Hello
I have installed the lesson58 on a fresh WP installation. Received the following error on activate:

`Fatal error: Uncaught Error: Class 'Inc\Base\Activate' not found in D:\xampp\htdocs\wordpress\wp-content\plugins\alecaddd-plugin\alecaddd-plugin.php:46 Stack trace: #0 D:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(286): activate_alecaddd_plugin('') #1 D:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #2 D:\xampp\htdocs\wordpress\wp-includes\plugin.php(465): WP_Hook->do_action(Array) #3 D:\xampp\htdocs\wordpress\wp-admin\plugins.php(177): do_action('activate_alecad...') #4 {main} thrown in D:\xampp\htdocs\wordpress\wp-content\plugins\alecaddd-plugin\alecaddd-plugin.php on line 46`

Thanks

**Comment by LifeSteala** [comment]
Resolved. Did not run `composer install`.

**Comment by ledoan19** [comment]
i too, thanks https://webaoe.com/

**Comment by assassinback** [comment]
I am trying to install my plugin on live server but it giving me this error on activation, its working fine on localhost
