### ISSUE TITLE
Fatal error: Uncaught Error: Class "Inc\Base\Activate" not found in

### ISSUE THREAD

**Issue by sumeetbhardwaj** [Alecaddd/WordPressPlugin101#20]
Hi!  Sir
When i activate this plugin. I found this error. Please tell me solution.

Fatal error: Uncaught Error: Class "Inc\Base\Activate" not found in C:\xampp\htdocs\wpschool\wp-content\plugins\alecaddd-plugin\alecaddd-plugin.php:46 Stack trace: #0 C:\xampp\htdocs\wpschool\wp-includes\class-wp-hook.php(292): activate_alecaddd_plugin('') #1 C:\xampp\htdocs\wpschool\wp-includes\class-wp-hook.php(316): WP_Hook->apply_filters('', Array) #2 C:\xampp\htdocs\wpschool\wp-includes\plugin.php(484): WP_Hook->do_action(Array) #3 C:\xampp\htdocs\wpschool\wp-admin\plugins.php(193): do_action('activate_alecad...') #4 {main} thrown in C:\xampp\htdocs\wpschool\wp-content\plugins\alecaddd-plugin\alecaddd-plugin.php on line 46

**Comment by Alecaddd** [comment]
Did you run `compose install`?

I see you're using XAMPP, which I'm not sure supports composer.
Also, this is not a ready to use plugin but it's a repository for the YouTube tutorials I did to show how to build a plugin with PHP OOP.
