### ISSUE TITLE
multi settings in admin page

### ISSUE THREAD

**Issue by Mohammadreza-73** [Alecaddd/WordPressPlugin101#23]
Hi,
How to create multi separated admin settings:
![Capture](https://user-images.githubusercontent.com/22294125/123545826-53129300-d76f-11eb-984e-84fde05e7694.JPG)

i mean create settings form on each tab

**Comment by Alecaddd** [comment]
Did you watch my entire tutorial?

**Comment by Mohammadreza-73** [comment]
Up to lesson 30
