### ISSUE TITLE
Some Love

### ISSUE THREAD

**Issue by ghost** [Alecaddd/WordPressPlugin101#6]
Man (or guys) i just wanted to say that your tutorials are amazing. Thank you for the great effort.
<3

**Comment by ghost** [comment]
And another issue is:


Fatal error: Uncaught Error: Class 'Inc\Base\Activate' not found in /var/www/html/wp-content/plugins/alacaddd-plugin/alecaddd-plugin.php:46 Stack trace: #0 /var/www/html/wp-includes/class-wp-hook.php(286): activate_alecaddd_plugin('') #1 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #2 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /var/www/html/wp-admin/plugins.php(174): do_action('activate_alacad...') #4 {main} thrown in /var/www/html/wp-content/plugins/alacaddd-plugin/alecaddd-plugin.php on line 46

When I am activating your plugin. ( I use Wordpress 4.9 , php7 )

**Comment by ghost** [comment]
FIX: run `composer install` from your terminal in the alecaddd-plugin dir

**Comment by ghost** [comment]
Guys I almost love you so much for these tutorials :)

**Comment by Alecaddd** [comment]
Hi, thank you for the message, that's just me and no one else.
Happy Coding
